### ISSUE TITLE
RSI_BULL_BEAR_ADX Needs Latest Update

### ISSUE THREAD

**Issue by BradT7** [Gab0/gekko-adapted-strategies#1]
Hi Gab,

I just noticed this whole time while I was using your wonderfully speedy adapted strategies your ADX strategy is using an older version of Tommie's version. https://github.com/tommiehansen/gekko_tools 

He has since updated the latest one allowing for custom MODs of RLI depending on ADX, and therefore 4 more variables for Japonicus to play with.

You currently have those values hard codded in your version of the script. Not sure if this was intentional or not.

I compared the original version to your version and I tweaked the following lines of your code, and looks like the GA's are running okay with your version still!

```
// ADX
this.addIndicator('adx', 'ADX', this.settings.ADX )

		// MOD (RSI modifiers)
		this.BULL_MOD_high = this.settings.BULL_MOD_high;
		this.BULL_MOD_low = this.settings.BULL_MOD_low;
		this.BEAR_MOD_high = this.settings.BEAR_MOD_high;
		this.BEAR_MOD_low = this.settings.BEAR_MOD_low;

// BEAR TREND
		// ADX trend strength?
		if( adx > this.settings.ADX_high ) rsi_hi = rsi_hi + this.BEAR_MOD_high;
		else if( adx < this.settings.ADX_low ) rsi_low = rsi_low + this.BEAR_MOD_low;
// BULL TREND
		// ADX trend strength?
		if( adx > this.settings.ADX_high ) rsi_hi = rsi_hi + this.BULL_MOD_high;		
		else if( adx < this.settings.ADX_low ) rsi_low = rsi_low + this.BULL_MOD_low;
```

And added the following in the configStrategies.py (which is how I had it configured prior)
Please note if adding in to your version, the MOD values cannot be 1, otherwise the script/GAs fail.
So an auto percent range might be an issue here if it chooses a value of 1 in the GA epochs.
```
# MODIFY RSI (depending on ADX)
"BULL_MOD_high": (2,10), # 5
"BULL_MOD_low": (-10,-2), # -5
"BEAR_MOD_high": (5,20), # 15
"BEAR_MOD_low": (-10,-2), # -5
```

Regards

**Comment by Gab0** [comment]
Thanks, I need to be kept informed like that ;D. I'm uploading the adapted new version. Props to tommiehansen. And @BradT7 OFC
